FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum /app/
COPY ./cmd/ /app/cmd/
COPY ./internal/ /app/internal/
COPY ./api/ /app/api/
COPY ./web/ /app/web/

ENV CGO_ENABLED=0
RUN go build -gcflags "all=-N -l" -o app cmd/runner/main.go
RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM scratch

COPY --from=builder /app/app /app/
COPY --from=builder /go/bin/dlv /go/bin/dlv

ENTRYPOINT ["/go/bin/dlv", "exec", "/app/app", "--headless", "--listen=:40000", "--api-version=2", "--accept-multiclient"]
