services:
  mysql:
    image: mysql:9.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql

  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres/data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:25.7
    container_name: clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: db
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: pass
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./tmp/clickhouse/data:/var/lib/clickhouse
      - ./tmp/clickhouse/logs:/var/log/clickhouse-server

  mongo:
    image: mongo:8.0.13
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/mongo:/data/db

  app:
    build:
      context: .
      #dockerfile: Dockerfile
      #dockerfile: Dockerfile-dlv for testing in docker
      dockerfile: Dockerfile-vscode
    container_name: app
    restart: unless-stopped
    environment:
      DB: postgres
      SERVER: net_http
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: db
      STORAGE_PATH: /storage
      IP: 0.0.0.0
      PORT: 80
    ports:
      - "8000:80"
      - "8080:8080"
      - "10000:22"
      #- "40000:40000" for testing in docker
    depends_on:
      - mysql
      - postgres
      - mongo
    volumes:
      - ./tmp/storage:/storage
      - .:/home/dev/go-template