// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AddProductResponse struct {
	ID string `json:"id"`
}

type MessageResponse struct {
	Msg string `json:"msg"`
}

type Mutation struct {
}

type ProductFilter struct {
	ID string `json:"id"`
}

type Query struct {
}

type Subscription struct {
}
